language: node_js
sudo: false
node_js:
- 4.4.0
before_install:
  - 'openssl aes-256-cbc -K $encrypted_989954bb41cf_key -iv $encrypted_989954bb41cf_iv -in auth.js.enc -out test/resources/auth.js -d'
script:
- npm run test:codecov
- npm run test:selenium:travis
after_success:
  - jsdoc/publish.sh
  - bash <(curl -s https://codecov.io/bash)
after_script:
  # hacky workaround for hanging chromedriver processes
  - pkill chromedriver
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
      - ewinters@us.ibm.com
      - najimovi@ar.ibm.com
    on_success: always    # default is change, update if this gets too annoying
    on_failure: always    # default: always
addons:
  sauce_connect: true
